### ISSUE TITLE
release Github action fails with "Server redirected too many  times"

### ISSUE THREAD

**Issue by mccartney** [sksamuel/scapegoat#383]
```
2020-06-17T20:44:43.1985490Z [info] Main Scala API documentation successful.
2020-06-17T20:44:50.7052897Z [warn] three warnings found
2020-06-17T20:44:51.0808371Z [info] Done compiling.
2020-06-17T20:44:53.5063473Z [info] Wrote /home/runner/work/scapegoat/scapegoat/target/scala-2.11.12/scalac-scapegoat-plugin_2.11.12-1.4.4+21-5750a811-SNAPSHOT.pom
2020-06-17T20:44:54.7533328Z [error] java.net.ProtocolException: Server redirected too many  times (20)
2020-06-17T20:44:54.7534356Z [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2020-06-17T20:44:54.7534935Z [error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2020-06-17T20:44:54.7535429Z [error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2020-06-17T20:44:54.7536061Z [error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2020-06-17T20:44:54.7536955Z [error] 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
2020-06-17T20:44:54.7537611Z [error] 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
2020-06-17T20:44:54.7538430Z [error] 	at java.security.AccessController.doPrivileged(Native Method)
2020-06-17T20:44:54.7539549Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
2020-06-17T20:44:54.7540492Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
2020-06-17T20:44:54.7541106Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
2020-06-17T20:44:54.7541672Z [error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
2020-06-17T20:44:54.7542291Z [error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
2020-06-17T20:44:54.7543350Z [error] 	at java.security.AccessController.doPrivileged(Native Method)
2020-06-17T20:44:54.7543863Z [error] 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
2020-06-17T20:44:54.7544378Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
2020-06-17T20:44:54.7544871Z [error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
2020-06-17T20:44:54.7545412Z [error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:285)
2020-06-17T20:44:54.7545875Z [error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
2020-06-17T20:44:54.7546559Z [error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
2020-06-17T20:44:54.7547179Z [error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
2020-06-17T20:44:54.7547745Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:368)
2020-06-17T20:44:54.7548413Z [error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
2020-06-17T20:44:54.7548951Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
2020-06-17T20:44:54.7549661Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
2020-06-17T20:44:54.7550145Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
2020-06-17T20:44:54.7550701Z [error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
2020-06-17T20:44:54.7551156Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
2020-06-17T20:44:54.7551644Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
2020-06-17T20:44:54.7552098Z [error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
2020-06-17T20:44:54.7552527Z [error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
2020-06-17T20:44:54.7553076Z [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
2020-06-17T20:44:54.7553887Z [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
2020-06-17T20:44:54.7554331Z [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
2020-06-17T20:44:54.7554832Z [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
2020-06-17T20:44:54.7555268Z [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
2020-06-17T20:44:54.7555793Z [error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
2020-06-17T20:44:54.7556442Z [error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:500)
2020-06-17T20:44:54.7557071Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:142)
2020-06-17T20:44:54.7557587Z [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2020-06-17T20:44:54.7558027Z [error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:156)
2020-06-17T20:44:54.7558662Z [error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:149)
2020-06-17T20:44:54.7559153Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:142)
2020-06-17T20:44:54.7559859Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:132)
2020-06-17T20:44:54.7560831Z [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:251)
2020-06-17T20:44:54.7561302Z [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:215)
2020-06-17T20:44:54.7561652Z [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:77)
2020-06-17T20:44:54.7562031Z [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:87)
2020-06-17T20:44:54.7562389Z [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
2020-06-17T20:44:54.7562723Z [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
2020-06-17T20:44:54.7563123Z [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
2020-06-17T20:44:54.7563462Z [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
2020-06-17T20:44:54.7564002Z [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
2020-06-17T20:44:54.7564395Z [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
2020-06-17T20:44:54.7564725Z [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
2020-06-17T20:44:54.7565106Z [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
2020-06-17T20:44:54.7565424Z [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
2020-06-17T20:44:54.7565741Z [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
2020-06-17T20:44:54.7566116Z [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
2020-06-17T20:44:54.7566646Z [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
2020-06-17T20:44:54.7567207Z [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
2020-06-17T20:44:54.7567560Z [error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:132)
2020-06-17T20:44:54.7567917Z [error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2814)
2020-06-17T20:44:54.7568297Z [error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2814)
2020-06-17T20:44:54.7568617Z [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2020-06-17T20:44:54.7569023Z [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2020-06-17T20:44:54.7569364Z [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
2020-06-17T20:44:54.7569850Z [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
2020-06-17T20:44:54.7570212Z [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
2020-06-17T20:44:54.7570521Z [error] 	at sbt.Execute.work(Execute.scala:290)
2020-06-17T20:44:54.7571112Z [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
2020-06-17T20:44:54.7571472Z [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020-06-17T20:44:54.7571802Z [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020-06-17T20:44:54.7572165Z [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-17T20:44:54.7572488Z [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-06-17T20:44:54.7572856Z [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-17T20:44:54.7573196Z [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-17T20:44:54.7573544Z [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-17T20:44:54.7574095Z [error] 	at java.lang.Thread.run(Thread.java:748)
2020-06-17T20:44:54.7574415Z [error] Caused by: java.net.ProtocolException: Server redirected too many  times (20)
2020-06-17T20:44:54.7574891Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1908)
2020-06-17T20:44:54.7575272Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
2020-06-17T20:44:54.7575665Z [error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
2020-06-17T20:44:54.7576057Z [error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
2020-06-17T20:44:54.7576581Z [error] 	at java.security.AccessController.doPrivileged(Native Method)
2020-06-17T20:44:54.7577180Z [error] 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
2020-06-17T20:44:54.7577539Z [error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
2020-06-17T20:44:54.7577910Z [error] 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
2020-06-17T20:44:54.7578323Z [error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
2020-06-17T20:44:54.7578672Z [error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:281)
2020-06-17T20:44:54.7579241Z [error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
2020-06-17T20:44:54.7579732Z [error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
2020-06-17T20:44:54.7580070Z [error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
2020-06-17T20:44:54.7580482Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:368)
2020-06-17T20:44:54.7580820Z [error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
2020-06-17T20:44:54.7581218Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
2020-06-17T20:44:54.7581574Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
2020-06-17T20:44:54.7581986Z [error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
2020-06-17T20:44:54.7582367Z [error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
2020-06-17T20:44:54.7582710Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
2020-06-17T20:44:54.7583095Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
2020-06-17T20:44:54.7583427Z [error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
2020-06-17T20:44:54.7584171Z [error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
2020-06-17T20:44:54.7584497Z [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
2020-06-17T20:44:54.7584974Z [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
2020-06-17T20:44:54.7585324Z [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
2020-06-17T20:44:54.7585735Z [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
2020-06-17T20:44:54.7586072Z [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
2020-06-17T20:44:54.7586645Z [error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
2020-06-17T20:44:54.7587147Z [error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:500)
2020-06-17T20:44:54.7587570Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:142)
2020-06-17T20:44:54.7587916Z [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2020-06-17T20:44:54.7588461Z [error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:156)
2020-06-17T20:44:54.7588875Z [error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:149)
2020-06-17T20:44:54.7589357Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:142)
2020-06-17T20:44:54.7589990Z [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:132)
2020-06-17T20:44:54.7590385Z [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:251)
2020-06-17T20:44:54.7590767Z [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:215)
2020-06-17T20:44:54.7591093Z [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:77)
2020-06-17T20:44:54.7591423Z [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:87)
2020-06-17T20:44:54.7591824Z [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
2020-06-17T20:44:54.7592164Z [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
2020-06-17T20:44:54.7592515Z [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
2020-06-17T20:44:54.7592897Z [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
2020-06-17T20:44:54.7593250Z [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
2020-06-17T20:44:54.7593517Z [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
2020-06-17T20:44:54.7594092Z [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
2020-06-17T20:44:54.7594490Z [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
2020-06-17T20:44:54.7594759Z [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
2020-06-17T20:44:54.7595129Z [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
2020-06-17T20:44:54.7595506Z [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
2020-06-17T20:44:54.7595845Z [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
2020-06-17T20:44:54.7596194Z [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
2020-06-17T20:44:54.7596823Z [error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:132)
2020-06-17T20:44:54.7597316Z [error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2814)
2020-06-17T20:44:54.7597647Z [error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2814)
2020-06-17T20:44:54.7598027Z [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2020-06-17T20:44:54.7598428Z [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2020-06-17T20:44:54.7598715Z [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
2020-06-17T20:44:54.7599110Z [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
2020-06-17T20:44:54.7599663Z [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
2020-06-17T20:44:54.7599986Z [error] 	at sbt.Execute.work(Execute.scala:290)
2020-06-17T20:44:54.7600297Z [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
2020-06-17T20:44:54.7600841Z [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020-06-17T20:44:54.7601181Z [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020-06-17T20:44:54.7601552Z [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-17T20:44:54.7601924Z [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-06-17T20:44:54.7602290Z [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-17T20:44:54.7602779Z [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-17T20:44:54.7603118Z [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-17T20:44:54.7604067Z [error] 	at java.lang.Thread.run(Thread.java:748)
2020-06-17T20:44:54.7604457Z [error] (publish) java.net.ProtocolException: Server redirected too many  times (20)
2020-06-17T20:44:54.7732382Z [error] Total time: 36 s, completed Jun 17, 2020 8:44:54 PM
2020-06-17T20:44:55.1012148Z ##[error]Process completed with exit code 1.
2020-06-17T20:44:55.1076137Z Post job cleanup.
```
can be observed in recent runs of the Release Github action.

**Comment by mccartney** [comment]
Not sure why do we release anything on any push to repository.

**Comment by mwz** [comment]
> Not sure why do we release anything on any push to repository.

We release a snapshot for each merged PR for those who want to use it for testing and not having to wait for new releases.

It looks like it started failing two weeks ago with the following message ([full log](https://github.com/sksamuel/scapegoat/runs/739836955?check_suite_focus=true)):
>Access to URL https://oss.sonatype.org/content/repositories/snapshots/com/***/scapegoat/scalac-scapegoat-plugin_2.11.12/1.4.4%2B10-7098050f-SNAPSHOT/scalac-scapegoat-plugin_2.11.12-1.4.4%2B10-7098050f-SNAPSHOT.pom was refused by the server: Unauthorized

which makes me think that maybe sonatype creds have expired? @sksamuel are you aware of any recent changes or did you reset/change your sonatype password?

**Comment by sksamuel** [comment]
I don't think the password changed but I will reset it and update travis.

**Comment by sksamuel** [comment]
I say travis, I mean github secrets. So done that now. I'll force a build through to see.

**Comment by sksamuel** [comment]
Ok that worked. Closing.
